# -*- coding: utf-8 -*-
"""EDA of project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cFRY6YyPMpijD4W6DINZtX0ux898s9m
"""

# ==============================================================================
# Script: Exploratory Data Analysis (EDA) for Air Quality & Weather
# Author: Data Analysis Team
# Description: This script processes Gold Layer data and generates a 5-page
#              analytical report simulating a Power BI dashboard structure.
# ==============================================================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Configure visual settings for professional reporting
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

print("Initializing Data Load from Gold Layer...")
try:
    dim_location = pd.read_csv("dim_location.csv")
    dim_date = pd.read_csv("dim_date.csv", parse_dates=['date'])
    fact_table = pd.read_csv("fact_table.csv", parse_dates=['date'])

    # Denormalize tables for EDA
    df = fact_table.merge(dim_location, on='location_key', how='inner') \
                   .merge(dim_date, on='date', how='inner')
    print(f"Data successfully loaded and merged. Total observations: {len(df)}")
except Exception as e:
    print(f"Error loading data: {e}")
    exit()

print("-" * 80)

# ==============================================================================
# PAGE 1: Overview & High-Level KPIs
# ==============================================================================
print("\n--- PAGE 1: OVERVIEW & HIGH-LEVEL KPIs ---")
print("Business Questions:")
print("1. What is the total scope of the dataset (records, locations)?")
print("2. What is the overall average Air Quality Index (AQI)?")
print("3. What is the overall average Temperature?")
print("4. How are the air quality categories distributed across the dataset?")
print("\nKey Performance Indicators (KPIs):")

print(f"- Total Records: {len(df)}")
print(f"- Unique Countries Covered: {df['country'].nunique()}")
print(f"- Unique Cities Covered: {df['city'].nunique()}")

if 'AQI' in df.columns:
    print(f"- Overall Average AQI: {df['AQI'].mean():.2f}")
if 'temperature' in df.columns:
    print(f"- Overall Average Temperature: {df['temperature'].mean():.2f} C")

# Visualizations
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

if 'AQI_label' in df.columns:
    sns.countplot(data=df, x='AQI_label', palette='viridis', order=df['AQI_label'].value_counts().index, ax=axes[0])
    axes[0].set_title("Distribution of Air Quality Categories")
    axes[0].tick_params(axis='x', rotation=45)
    axes[0].set_ylabel("Count of Records")

if 'AQI' in df.columns:
    sns.histplot(data=df, x='AQI', bins=30, kde=True, color='indigo', ax=axes[1])
    axes[1].set_title("Histogram: Distribution of AQI Values")

plt.tight_layout()
plt.show()
print("-" * 80)

# ==============================================================================
# PAGE 2: Geographical Analysis
# ==============================================================================
print("\n--- PAGE 2: GEOGRAPHICAL ANALYSIS ---")
print("Business Questions:")
print("1. Which 10 countries suffer from the highest average pollution levels?")
print("2. Which 5 countries record the cleanest air quality?")
print("3. What is the variance in air quality within the most polluted countries?")
print("4. Which specific city holds the highest average AQI?")
print("\nKey Performance Indicators (KPIs):")

if 'country' in df.columns and 'AQI' in df.columns:
    country_aqi = df.groupby('country')['AQI'].mean().sort_values(ascending=False).reset_index()
    city_aqi = df.groupby(['country', 'city'])['AQI'].mean().sort_values(ascending=False).reset_index()

    print(f"- Highest Polluted Country: {country_aqi.iloc[0]['country']} (Avg AQI: {country_aqi.iloc[0]['AQI']:.2f})")
    print(f"- Cleanest Country: {country_aqi.iloc[-1]['country']} (Avg AQI: {country_aqi.iloc[-1]['AQI']:.2f})")
    print(f"- Most Polluted City: {city_aqi.iloc[0]['city']}, {city_aqi.iloc[0]['country']} (Avg AQI: {city_aqi.iloc[0]['AQI']:.2f})")

    # Visualizations
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    sns.barplot(data=country_aqi.head(10), x='AQI', y='country', palette='Reds_r', ax=axes[0])
    axes[0].set_title("Top 10 Polluted Countries")

    sns.barplot(data=country_aqi.tail(5), x='AQI', y='country', palette='Greens_r', ax=axes[1])
    axes[1].set_title("Top 5 Cleanest Countries")

    worst_5_countries = country_aqi.head(5)['country'].tolist()
    sns.boxplot(data=df[df['country'].isin(worst_5_countries)], x='country', y='AQI', palette='Reds', ax=axes[2])
    axes[2].set_title("AQI Variance in Top 5 Polluted Countries")

    plt.tight_layout()
    plt.show()
print("-" * 80)

# ==============================================================================
# PAGE 3: Temporal Trends
# ==============================================================================
print("\n--- PAGE 3: TEMPORAL TRENDS ---")
print("Business Questions:")
print("1. How does the average AQI fluctuate month over month?")
print("2. Is there a visual alignment between temperature changes and AQI changes?")
print("3. Which month records the worst air quality, and which records the highest temperature?")
print("4. How does air quality differ across various seasons?")
print("\nKey Performance Indicators (KPIs):")

if 'month_name' in df.columns and 'temperature' in df.columns:
    monthly_trend = df.groupby(['month', 'month_name'])[['AQI', 'temperature']].mean().reset_index().sort_values('month')
    worst_month = monthly_trend.loc[monthly_trend['AQI'].idxmax()]
    hot_month = monthly_trend.loc[monthly_trend['temperature'].idxmax()]

    print(f"- Peak Pollution Month: {worst_month['month_name']} (Avg AQI: {worst_month['AQI']:.2f})")
    print(f"- Peak Temperature Month: {hot_month['month_name']} (Avg Temp: {hot_month['temperature']:.2f} C)")

    # Visualizations
    fig, axes = plt.subplots(1, 2, figsize=(16, 5))

    ax1 = axes[0]
    sns.lineplot(data=monthly_trend, x='month_name', y='AQI', marker='o', color='firebrick', ax=ax1, label='AQI')
    ax1.set_ylabel("Average AQI", color='firebrick')
    ax2 = ax1.twinx()
    sns.barplot(data=monthly_trend, x='month_name', y='temperature', alpha=0.3, color='steelblue', ax=ax2)
    ax2.set_ylabel("Temperature (C)", color='steelblue')
    ax1.set_title("Monthly Trend: AQI vs Temperature")
    ax1.tick_params(axis='x', rotation=45)

    if 'season' in df.columns:
        sns.boxplot(data=df, x='season', y='AQI', palette='Set2', ax=axes[1])
        axes[1].set_title("Air Quality Variation by Season")

    plt.tight_layout()
    plt.show()
print("-" * 80)

# ==============================================================================
# PAGE 4: Correlation Analysis
# ==============================================================================
print("\n--- PAGE 4: CORRELATION ANALYSIS ---")
print("Business Questions:")
print("1. Which weather variable has the strongest correlation with air pollution?")
print("2. Does higher temperature directly correlate with higher AQI?")
print("3. Is there a significant relationship between specific pollutants like PM10 and NO2?")
print("4. Does humidity level impact the overall air quality?")
print("\nKey Performance Indicators (KPIs):")

weather_cols = ['temperature', 'pressure', 'humidity', 'pm10', 'no2', 'AQI']
avail_cols = [c for c in weather_cols if c in df.columns]

if len(avail_cols) > 1:
    corr_matrix = df[avail_cols].corr()
    print("- Correlation matrix calculated successfully across available metrics.")

    # Visualizations
    fig, axes = plt.subplots(1, 2, figsize=(15, 6))

    sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5, ax=axes[0])
    axes[0].set_title("Correlation Heatmap: Weather Metrics vs Pollution")

    if 'temperature' in avail_cols and 'AQI' in avail_cols:
        sns.scatterplot(data=df, x='temperature', y='AQI', alpha=0.4, color='chocolate', ax=axes[1])
        sns.regplot(data=df, x='temperature', y='AQI', scatter=False, color='maroon', ax=axes[1])
        axes[1].set_title("Regression Analysis: Temperature vs AQI")

    plt.tight_layout()
    plt.show()
print("-" * 80)

# ==============================================================================
# PAGE 5: Workdays Analysis & Specific Pollutants
# ==============================================================================
print("\n--- PAGE 5: WORKDAYS ANALYSIS & SPECIFIC POLLUTANTS ---")
print("Business Questions:")
print("1. Is there a significant difference in air quality between weekdays and weekends?")
print("2. What is the average concentration of PM10 across all records?")
print("3. What is the average concentration of NO2 across all records?")
print("4. How widespread are extreme values (outliers) in specific pollutants?")
print("\nKey Performance Indicators (KPIs):")

if 'is_weekday' in df.columns:
    day_type_aqi = df.groupby('is_weekday')['AQI'].mean().reset_index()
    day_type_aqi['Day_Type'] = day_type_aqi['is_weekday'].map({True: 'Weekday (Work)', False: 'Weekend (Holiday)'})

    for index, row in day_type_aqi.iterrows():
        print(f"- Average AQI on {row['Day_Type']}: {row['AQI']:.2f}")

    pollutants = ['pm10', 'no2']
    avail_polls = [p for p in pollutants if p in df.columns]

    for p in avail_polls:
        print(f"- Average {p.upper()} Concentration: {df[p].mean():.2f}")

    # Visualizations
    fig, axes = plt.subplots(1, 2, figsize=(15, 5))

    sns.barplot(data=day_type_aqi, x='Day_Type', y='AQI', palette='mako', ax=axes[0])
    axes[0].set_title("Comparison: Average AQI (Weekdays vs Weekends)")

    if avail_polls:
        melted_df = df.melt(value_vars=avail_polls, var_name='Pollutant', value_name='Concentration')
        sns.boxplot(data=melted_df, x='Pollutant', y='Concentration', palette='rocket', ax=axes[1])
        axes[1].set_title("Concentration Spread of Specific Pollutants")

        # Limit y-axis to handle extreme outliers for better visibility
        y_limit = df[avail_polls].quantile(0.95).max()
        if pd.notnull(y_limit):
            axes[1].set_ylim(0, y_limit * 1.2)

    plt.tight_layout()
    plt.show()

print("\nAnalysis Execution Completed.")
print("=" * 80)