# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCXLWon8roy6wE6Iq2eaGx4z5vqhdvcZ
"""

import pandas as pd
import numpy as np
import os

# المسارات والملفات الموحدة لخطوة الـ Gold
SILVER_FILE = "silver_layer.csv"
GOLD_DIR = "gold_layer/"

def build_gold_layer():
    print("\n============================================================")
    print("  GOLD LAYER — STAR SCHEMA GENERATION — START")
    print("============================================================\n")

    # إنشاء مجلد الـ Gold إذا لم يكن موجوداً
    if not os.path.exists(GOLD_DIR):
        os.makedirs(GOLD_DIR)

    print(f"[GOLD] Reading cleaned data from: {SILVER_FILE}")
    try:
        # قراءة ملف السيلفر المعدل الأخير
        df = pd.read_csv(SILVER_FILE)
        df['date'] = pd.to_datetime(df['date'])
    except FileNotFoundError:
        print(f"[GOLD] ✗ ERROR: Silver file not found: {SILVER_FILE}")
        print("[GOLD] يرجى التأكد من رفع ملف 'silver_layer.csv' أولاً في الـ Environment الخاص بكِ.")
        return
    except Exception as e:
        print(f"[GOLD] ✗ ERROR loading silver file: {e}")
        return

    # ------------------------------------------------------------
    # الخطوة 1: بناء جدول أبعاد المكان (Dim_Location)
    # ------------------------------------------------------------
    print("[GOLD] Step 1: Building Dim_Location ...")
    # استخراج الأماكن الفريدة بدون تكرار النصوص لبناء البُعد المكاني
    dim_location = df[['country', 'city']].drop_duplicates().reset_index(drop=True)
    dim_location['location_key'] = dim_location.index + 1  # Surrogate Key- need primary key for others
    dim_location = dim_location[['location_key', 'country', 'city']]

    # ------------------------------------------------------------
    # الخطوة 2: بناء جدول أبعاد الزمان (Dim_Date)
    # ------------------------------------------------------------
    print("[GOLD] Step 2: Building Dim_Date ...")
    # استخراج التواريخ والأبعاد الزمنية المحسوبة في السيلفر
    date_cols = ['date', 'is_weekday', 'month_name', 'season']
    dim_date = df[date_cols].drop_duplicates().reset_index(drop=True)

    # تفكيك التواريخ لأعمدة فرعية لمساعدتك في عمل الـ Hierarchies (سنة > شهر > يوم) داخل الـ Power BI
    dim_date['year'] = dim_date['date'].dt.year
    dim_date['month'] = dim_date['date'].dt.month
    dim_date['day'] = dim_date['date'].dt.day

    dim_date = dim_date[['date', 'year', 'month', 'month_name', 'day', 'is_weekday', 'season']]

    # ------------------------------------------------------------
    # الخطوة 3: بناء جدول الحقائق (Fact_AirQuality_Weather)
    # ------------------------------------------------------------
    print("[GOLD] Step 3: Building Fact_AirQuality_Weather ...")

    # ربط جدول الحقائق بجدول المكان للحصول على المفتاح التعريفي (location_key) واستبعاد النصوص المكررة
    fact_df = pd.merge(df, dim_location, on=['country', 'city'], how='left')

    # جلب جميع المقاييس الرقمية المتاحة للطقس والـ AQI
    weather_measures = ['temperature', 'pressure', 'humidity', 'dew', 'precipitation', 'wind gust', 'uvi']
    actual_weather = [c for c in weather_measures if c in fact_df.columns]
    aqi_measures = ['AQI', 'AQI_label', 'AQI_sort_order']

    # اختيار الأعمدة الرقمية والمفاتيح فقط تماشياً مع معايير الـ Data Modeling الاحترافية
    fact_columns = ['date', 'location_key'] + actual_weather + aqi_measures
    fact_table = fact_df[fact_columns].copy()

    # إضافة مفتاح خاص بجدول الحقائق نفسه (fact_key) كـ Surrogate Key
    fact_table.insert(0, 'fact_key', fact_table.index + 1)

    # ------------------------------------------------------------
    # الخطوة 4: تصدير وحفظ جداول الـ Star Schema الثلاثة
    # ------------------------------------------------------------
    print("[GOLD] Step 4: Exporting tables to gold directory ...")

    dim_location.to_csv(os.path.join(GOLD_DIR, "dim_location.csv"), index=False, encoding="utf-8")
    dim_date.to_csv(os.path.join(GOLD_DIR, "dim_date.csv"), index=False, encoding="utf-8")
    fact_table.to_csv(os.path.join(GOLD_DIR, "fact_airquality_weather.csv"), index=False, encoding="utf-8")

    print("\n============================================================")
    print("  ✓ GOLD LAYER GENERATION COMPLETED SUCCESSFULLY!")
    print(f"  Check your folder for '{GOLD_DIR}' containing your 3 Schema files:")
    print(f"   - dim_location.csv            ({len(dim_location)} rows)")
    print(f"   - dim_date.csv                ({len(dim_date)} rows)")
    print(f"   - fact_airquality_weather.csv ({len(fact_table)} rows)")
    print("============================================================\n")

if __name__ == "__main__":
    build_gold_layer()